"""Added unique constraint to el_criteria_has_criterion table.

Revision ID: 33779211b25c
Revises: c6ab788c04b3
Create Date: 2023-03-21 11:38:33.082413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33779211b25c'
down_revision = 'c6ab788c04b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('el_criteria_has_criterion_uix', 'el_criteria_has_criterion', ['criterion_id', 'eligibility_criteria_id', 'value_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('el_criteria_has_criterion_uix', 'el_criteria_has_criterion', type_='unique')
    # ### end Alembic commands ###
