"""Added country, status, city, state, zip to site model.

Revision ID: 3a26a8e3543c
Revises: 14f21c3d226d
Create Date: 2023-11-27 12:42:10.934316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a26a8e3543c'
down_revision = '14f21c3d226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('country', sa.String(), nullable=True))
    op.add_column('site', sa.Column('status', sa.String(), nullable=True))
    op.add_column('site', sa.Column('city', sa.String(), nullable=True))
    op.add_column('site', sa.Column('state', sa.String(), nullable=True))
    op.add_column('site', sa.Column('zip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'zip')
    op.drop_column('site', 'state')
    op.drop_column('site', 'city')
    op.drop_column('site', 'status')
    op.drop_column('site', 'country')
    # ### end Alembic commands ###
