"""Modified unique constraint code, type, value_string, unit, operator to value table.

Revision ID: 3c0909b78f1b
Revises: 77a9fbd47800
Create Date: 2022-12-19 13:18:47.679371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0909b78f1b'
down_revision = '77a9fbd47800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['code', 'type', 'unit', 'value_string', 'operator'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['code', 'unit'])
    # ### end Alembic commands ###
