"""Added unique constraint code, unit to value table.

Revision ID: 77a9fbd47800
Revises: e3e1f15dc40d
Create Date: 2022-12-17 15:55:41.557289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a9fbd47800'
down_revision = 'e3e1f15dc40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('value', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('value_code_unit_uix', 'value', ['code', 'unit'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.alter_column('value', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
