"""Removed fields from criterion_staging.

Revision ID: 7b8a2262145a
Revises: 4e35df2e1509
Create Date: 2024-08-14 13:28:19.090935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b8a2262145a'
down_revision = '4e35df2e1509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('last_updated_by_user_id', sa.Integer(), nullable=True))
    op.drop_column('criterion_staging', 'display_rules_priority')
    op.drop_column('criterion_staging', 'last_updated_by')
    op.drop_column('criterion_staging', 'triggered_by_path')
    op.drop_column('criterion_staging', 'tags')
    op.drop_column('criterion_staging', 'display_rules_version')
    op.drop_column('criterion_staging', 'triggered_by_values_id')
    op.drop_column('criterion_staging', 'triggered_by_criterion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('triggered_by_criterion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('triggered_by_values_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('display_rules_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('tags', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('triggered_by_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('last_updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('display_rules_priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('criterion_staging', 'last_updated_by_user_id')
    # ### end Alembic commands ###
