"""Modified criterion_staging model, added fields.

Revision ID: 8295f20f3a8e
Revises: 1868fd0574b6
Create Date: 2024-07-19 15:57:02.770523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8295f20f3a8e'
down_revision = '1868fd0574b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('tags', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('criterion_staging', sa.Column('values', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('criterion_staging', sa.Column('display_rules_priority', sa.Integer(), nullable=True))
    op.add_column('criterion_staging', sa.Column('display_rules_version', sa.Integer(), nullable=True))
    op.add_column('criterion_staging', sa.Column('triggered_by_criterion_id', sa.Integer(), nullable=True))
    op.add_column('criterion_staging', sa.Column('triggered_by_values_id', sa.Integer(), nullable=True))
    op.add_column('criterion_staging', sa.Column('triggered_by_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'triggered_by_path')
    op.drop_column('criterion_staging', 'triggered_by_values_id')
    op.drop_column('criterion_staging', 'triggered_by_criterion_id')
    op.drop_column('criterion_staging', 'display_rules_version')
    op.drop_column('criterion_staging', 'display_rules_priority')
    op.drop_column('criterion_staging', 'values')
    op.drop_column('criterion_staging', 'tags')
    # ### end Alembic commands ###
