"""Fixed constrait in site model to handle null equivalency for upsert.

Revision ID: ac81dbbaf229
Revises: a9788be5ee2a
Create Date: 2026-02-16 11:50:24.757010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac81dbbaf229'
down_revision = 'a9788be5ee2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('site_uix'), 'site', type_='unique')
    op.create_unique_constraint('site_uix', 'site', ['name', 'location_lat', 'location_long'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('site_uix', 'site', type_='unique')
    op.create_unique_constraint(op.f('site_uix'), 'site', ['name', 'zip'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
