"""Replaced 'active' with 'status' in the criterion model.

Revision ID: b8bd57248411
Revises: 769593c95076
Create Date: 2024-06-04 15:00:45.107022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8bd57248411'
down_revision = '769593c95076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    criterionStatus = postgresql.ENUM('ACTIVE','INACTIVE','IN_PROCESS',name='criterionStatus')
    criterionStatus.create(op.get_bind())

    op.add_column('criterion', sa.Column('status', postgresql.ENUM('ACTIVE', 'IN_PROCESS', 'INACTIVE', name='criterionStatus'), nullable=True))
    op.drop_column('criterion', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('criterion', 'status')
    # ### end Alembic commands ###
