"""Removed algorithm_engine table, added algorithm_logic JSONB and algorithm_version to study_algorithm_engine table.

Revision ID: c205936c3719
Revises: c29a92132615
Create Date: 2023-01-29 16:16:59.068731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c205936c3719'
down_revision = 'c29a92132615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('algorithm_engine')
    op.add_column('study_algorithm_engine', sa.Column('algorithm_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('study_algorithm_engine', sa.Column('algorithm_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_algorithm_engine', 'algorithm_version')
    op.drop_column('study_algorithm_engine', 'algorithm_logic')
    op.create_table('algorithm_engine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study_algorithm_engine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('algorithm_engine_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('algorithm_logic', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['study_algorithm_engine_id'], ['study_algorithm_engine.id'], name='algorithm_engine_study_algorithm_engine_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='algorithm_engine_pkey')
    )
    # ### end Alembic commands ###
