"""Changed criterion.status to criterion.active boolean.

Revision ID: d8e5ba24131d
Revises: b8bd57248411
Create Date: 2024-06-28 14:49:32.595291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8e5ba24131d'
down_revision = 'b8bd57248411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('criterion', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'IN_PROCESS', name='criterionStatus'), autoincrement=False, nullable=True))
    op.drop_column('criterion', 'active')
    # ### end Alembic commands ###
