"""Modified raw_criteria.raw_criteria to raw_criteria.data.

Revision ID: df430a91a455
Revises: 68407e9294af
Create Date: 2024-07-11 13:04:32.181647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df430a91a455'
down_revision = '68407e9294af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_criteria', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('raw_criteria', 'raw_criteria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_criteria', sa.Column('raw_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('raw_criteria', 'data')
    # ### end Alembic commands ###
