"""Merge point fix, all updates.

Revision ID: e9bcbadcabdf
Revises: 3a26a8e3543c
Create Date: 2024-04-02 16:32:01.547999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bcbadcabdf'
down_revision = '3a26a8e3543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority', name='priority_uix'),
    sa.UniqueConstraint('source', name='source_uix')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unit_name_uix')
    )
    op.add_column('site', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_constraint('site_uix', 'site', type_='unique')
    op.create_unique_constraint('site_uix', 'site', ['name', 'zip'])
    op.create_foreign_key('fk_site_source_id', 'site', 'source', ['source_id'], ['id'])
    op.drop_column('site', 'active')
    op.drop_column('site', 'status')
    op.drop_column('site', 'code')
    op.add_column('study', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_study_source_id', 'study', 'source', ['source_id'], ['id'])
    op.add_column('study_version', sa.Column('study_version_num', sa.Integer(), nullable=False))
    op.drop_column('study_version', 'study_version')
    op.add_column('value', sa.Column('is_numeric', sa.Boolean(), nullable=True))
    op.add_column('value', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.drop_constraint('value_code_uix', 'value', type_='unique')
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_num_unit_op_uix', 'value', ['is_numeric', 'unit_id', 'value_string', 'operator'])
    op.create_foreign_key('fk_value_unit_id', 'value', 'unit', ['unit_id'], ['id'])
    op.drop_column('value', 'unit')
    op.drop_column('value', 'code')
    op.drop_column('value', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('value', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('value', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_value_unit_id', 'value', type_='foreignkey')
    op.drop_constraint('value_num_unit_op_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['type', 'unit', 'value_string', 'operator'])
    op.create_unique_constraint('value_code_uix', 'value', ['code'])
    op.drop_column('value', 'unit_id')
    op.drop_column('value', 'is_numeric')
    op.add_column('study_version', sa.Column('study_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('study_version', 'study_version_num')
    op.drop_constraint('fk_study_source_id', 'study', type_='foreignkey')
    op.drop_column('study', 'source_id')
    op.add_column('site', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_site_source_id', 'site', type_='foreignkey')
    op.drop_constraint('site_uix', 'site', type_='unique')
    op.create_unique_constraint('site_uix', 'site', ['name', 'code'])
    op.drop_column('site', 'source_id')
    op.drop_table('unit')
    op.drop_table('source')
    # ### end Alembic commands ###
