"""Removed active column in eligibility_criteria_info, changed to status enum type

Revision ID: f3c7a489a0c0
Revises: 33779211b25c
Create Date: 2023-05-16 16:15:47.699485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3c7a489a0c0'
down_revision = '33779211b25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    eligibilityCriteriaInfoStatus = postgresql.ENUM('ACTIVE','INACTIVE','IN_PROCESS',name='eligibilityCriteriaInfoStatus')
    eligibilityCriteriaInfoStatus.create(op.get_bind())
    op.add_column('eligibility_criteria_info', sa.Column('status', postgresql.ENUM('ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibilityCriteriaInfoStatus'), nullable=False))
    op.drop_column('eligibility_criteria_info', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility_criteria_info', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('eligibility_criteria_info', 'status')
    
    eligibilityCriteriaInfoStatus = postgresql.ENUM('ACTIVE','INACTIVE','IN_PROCESS',name='eligibilityCriteriaInfoStatus')
    eligibilityCriteriaInfoStatus.drop(op.get_bind())
    # ### end Alembic commands ###
