"""Added unique constraints to study_links and site tables.

Revision ID: 0d8f98ceec8d
Revises: 728f01902d1c
Create Date: 2023-11-17 12:03:20.372998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8f98ceec8d'
down_revision = '728f01902d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('site_uix', 'site', ['name', 'code'])
    op.create_unique_constraint('study_link_uix', 'study_links', ['study_id', 'href'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_link_uix', 'study_links', type_='unique')
    op.drop_constraint('site_uix', 'site', type_='unique')
    # ### end Alembic commands ###
