"""Added create_date to study external id model.

Revision ID: 14f21c3d226d
Revises: 0d8f98ceec8d
Create Date: 2023-11-20 12:51:42.792072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f21c3d226d'
down_revision = '0d8f98ceec8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_external_id', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_external_id', 'create_date')
    # ### end Alembic commands ###
