"""Remove FK relationship between raw_criteria and criterion_staging, add FK relationship bt criterion_staging and eligibility_criteria.

Revision ID: 1868fd0574b6
Revises: a95cae06bff8
Create Date: 2024-07-16 14:16:08.570065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1868fd0574b6'
down_revision = 'a95cae06bff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('eligibility_criteria_id', sa.Integer(), nullable=False))
    op.drop_constraint('criterion_staging_raw_criteria_id_fkey', 'criterion_staging', type_='foreignkey')
    op.create_foreign_key('criterion_staging_eligibility_criteria_id_fkey', 'criterion_staging', 'eligibility_criteria', ['eligibility_criteria_id'], ['id'])
    op.drop_column('criterion_staging', 'model_type')
    op.drop_column('criterion_staging', 'annotation_type')
    op.drop_column('criterion_staging', 'raw_criteria_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('raw_criteria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('criterion_staging', sa.Column('annotation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('criterion_staging_eligibility_criteria_id_fkey', 'criterion_staging', type_='foreignkey')
    op.create_foreign_key('criterion_staging_raw_criteria_id_fkey', 'criterion_staging', 'raw_criteria', ['raw_criteria_id'], ['id'])
    op.drop_column('criterion_staging', 'eligibility_criteria_id')
    # ### end Alembic commands ###
