"""Added raw_criteria table and relationship to eligibility_criteria.

Revision ID: 1b17bb764a3f
Revises: d8e5ba24131d
Create Date: 2024-07-03 13:17:34.574062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b17bb764a3f'
down_revision = 'd8e5ba24131d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eligibility_criteria_id', sa.Integer(), nullable=True),
    sa.Column('raw_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['eligibility_criteria_id'], ['eligibility_criteria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eligibility_criteria_id', name='raw_criteria_uix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_criteria')
    # ### end Alembic commands ###
