"""Added create_date to raw_criteria model.

Revision ID: 241619ddac70
Revises: 7b8a2262145a
Create Date: 2024-10-02 13:44:57.139152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '241619ddac70'
down_revision = '7b8a2262145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_criteria', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_criteria', 'create_date')
    # ### end Alembic commands ###
