"""Added echc_ids to criterion_staging table.

Revision ID: 2f25a654c48d
Revises: 9081b74448eb
Create Date: 2025-03-06 15:50:02.745077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f25a654c48d'
down_revision = '9081b74448eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('echc_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'echc_ids')
    # ### end Alembic commands ###
