"""NEW TABLE: criterion_staging.

Revision ID: 3f15449b3069
Revises: df430a91a455
Create Date: 2024-07-15 12:42:48.405531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f15449b3069'
down_revision = 'df430a91a455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterion_staging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_criteria_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.String(), nullable=True),
    sa.Column('annotation_type', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('ontology_code_id', sa.Integer(), nullable=True),
    sa.Column('input_type_id', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('criterion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ),
    sa.ForeignKeyConstraint(['input_type_id'], ['input_type.id'], ),
    sa.ForeignKeyConstraint(['ontology_code_id'], ['ontology_code.id'], ),
    sa.ForeignKeyConstraint(['raw_criteria_id'], ['raw_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criterion_staging')
    # ### end Alembic commands ###
