"""Modified STUDY_ALGORITHM_ENGINE.algorithm_logic type from JSONB to JSON because JSONB does not preserve order.

Revision ID: 41d465e25870
Revises: c205936c3719
Create Date: 2023-02-02 15:12:05.134993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41d465e25870'
down_revision = 'c205936c3719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_algorithm_engine', 'algorithm_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_algorithm_engine', 'algorithm_logic',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
