"""Added last_updated_by to criterion_staging.

Revision ID: 4e35df2e1509
Revises: eb4f4e85f0e4
Create Date: 2024-08-06 11:27:07.730733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e35df2e1509'
down_revision = 'eb4f4e85f0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('last_updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'last_updated_by')
    # ### end Alembic commands ###
