"""Added not null constraint to study_version.status and eligibility_criteria.status.

Revision ID: 4ff089373353
Revises: 241619ddac70
Create Date: 2024-11-07 12:46:42.837498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ff089373353'
down_revision = '241619ddac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### The following DML is required to ensure that legacy (manually entered) studies ###
    # ### have the study_version.status and eligibility_criteria.status attributes set ###
    # ### before the migration creates not null constraints on these columns in the db ###

    op.execute("UPDATE study_version SET status = 'ACTIVE' WHERE study_id IN \
		( \
			SELECT study_id FROM study s, study_external_id sei WHERE sei.study_id = s.id and sei.ext_id IN \
			( 'NCT04726241', 'NCT04898894', 'NCT04915612', 'NCT05183035', 'NCT05188170', 'NCT05101551', 'NCT02914405', 'NCT04239040', 'NCT04377932', 'NCT04928677') \
		)" 
	)
    op.execute("UPDATE study_version SET status = 'INACTIVE' WHERE study_id IN \
		( \
			SELECT study_id FROM study s, study_external_id sei WHERE sei.study_id = s.id and sei.ext_id IN \
			('NCT03194932', 'NCT03263936', 'NCT04678336', 'NCT04751383', 'NCT03478462', 'NCT03107988') \
		)"
	)

    op.execute("UPDATE eligibility_criteria SET status = 'ACTIVE' WHERE id IN \
		(SELECT sv.eligibility_criteria_id from study_version sv, study s, study_external_id e \
			WHERE s.id = sv.study_id and s.id = e.study_id AND e.ext_id IN \
		('NCT04726241', 'NCT04898894', 'NCT04915612', 'NCT05183035', 'NCT05188170', 'NCT05101551', 'NCT02914405', 'NCT04239040', 'NCT04377932', 'NCT04928677', \
			'NCT03194932', 'NCT03263936', 'NCT04678336', 'NCT04751383', 'NCT03478462', 'NCT03107988'))"
	)

    op.execute("UPDATE criterion set active = true where active is null")


    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)

    op.execute("""
        UPDATE eligibility_criteria
        SET status = 'NEW'
        WHERE status IS NULL;
    """)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=False)

    op.execute("""
        UPDATE study_version
        SET status = 'NEW'
        WHERE status IS NULL;
    """)
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=True)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=True)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
