"""Added eligibility_criteria_info table, modified study_algorithm_engine and eligibility_criteria.

Revision ID: 5f38941a18aa
Revises: 1aa0e74815e7
Create Date: 2023-03-11 22:39:51.977047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f38941a18aa'
down_revision = '1aa0e74815e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eligibility_criteria_study_version_id_fkey', 'eligibility_criteria', type_='foreignkey')
    op.drop_column('eligibility_criteria', 'study_version_id')
    op.drop_column('eligibility_criteria', 'active')
    op.drop_constraint('study_algorithm_engine_study_version_id_fkey', 'study_algorithm_engine', type_='foreignkey')
    op.drop_column('study_algorithm_engine', 'study_version_id')
    op.drop_column('study_algorithm_engine', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_algorithm_engine', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('study_algorithm_engine', sa.Column('study_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('study_algorithm_engine_study_version_id_fkey', 'study_algorithm_engine', 'study_version', ['study_version_id'], ['id'])
    op.add_column('eligibility_criteria', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('eligibility_criteria', sa.Column('study_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('eligibility_criteria_study_version_id_fkey', 'eligibility_criteria', 'study_version', ['study_version_id'], ['id'])
    # ### end Alembic commands ###
