"""Added table study_external_ids.

Revision ID: 60a3569ba935
Revises: d18095fc6bbb
Create Date: 2023-11-07 09:45:01.953713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a3569ba935'
down_revision = 'a20394e0f900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_external_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('ext_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'ext_id', name='study_ext_id_uix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_external_id')
    # ### end Alembic commands ###
