"""Modified study_external_id unique constraint.

Revision ID: 68407e9294af
Revises: d5b44fcd85b6
Create Date: 2024-07-10 12:41:40.202360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68407e9294af'
down_revision = 'd5b44fcd85b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_ext_id_uix', 'study_external_id', type_='unique')
    op.create_unique_constraint('study_ext_id_uix', 'study_external_id', ['ext_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_ext_id_uix', 'study_external_id', type_='unique')
    op.create_unique_constraint('study_ext_id_uix', 'study_external_id', ['study_id', 'ext_id'])
    # ### end Alembic commands ###
