"""Addded name to saved_input model.

Revision ID: 769593c95076
Revises: e9bcbadcabdf
Create Date: 2024-04-17 11:52:05.431620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769593c95076'
down_revision = 'e9bcbadcabdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_input', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_input', 'name')
    # ### end Alembic commands ###
