"""Added pre-annotated tables for matched models changes.

Revision ID: 9081b74448eb
Revises: d1044e7926c5
Create Date: 2025-02-10 13:42:05.166248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9081b74448eb'
down_revision = 'd1044e7926c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_annotated_criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_criteria_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_standard_gb_var', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['raw_criteria_id'], ['raw_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_annotated_criterion_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pre_annotated_criterion_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pre_annotated_criterion_id'], ['pre_annotated_criterion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_annotated_criterion_model')
    op.drop_table('pre_annotated_criterion')
    # ### end Alembic commands ###
