"""Moved input_id from criterion_staging to raw_criteria.

Revision ID: a117ad8d4dda
Revises: 2f25a654c48d
Create Date: 2025-03-19 15:06:56.021135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a117ad8d4dda'
down_revision = '2f25a654c48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'input_id')
    op.add_column('raw_criteria', sa.Column('input_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_criteria', 'input_id')
    op.add_column('criterion_staging', sa.Column('input_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
