"""Added lat long to site.

Revision ID: a9788be5ee2a
Revises: ddada803c81e
Create Date: 2025-10-09 10:51:16.551141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9788be5ee2a'
down_revision = 'ddada803c81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('location_lat', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('site', sa.Column('location_long', sa.DECIMAL(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'location_long')
    op.drop_column('site', 'location_lat')
    # ### end Alembic commands ###
