"""Added eligibility_criteria fk constraint and fk constraint names to eligibility_criteria_info table.

Revision ID: c6ab788c04b3
Revises: 5f38941a18aa
Create Date: 2023-03-14 19:34:36.154198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ab788c04b3'
down_revision = '5f38941a18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_criteria_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('study_version_id', sa.Integer(), nullable=True),
    sa.Column('study_algorithm_engine_id', sa.Integer(), nullable=True),
    sa.Column('eligibility_criteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eligibility_criteria_id'], ['eligibility_criteria.id'], name='fk_eligibility_criteria_id'),
    sa.ForeignKeyConstraint(['study_algorithm_engine_id'], ['study_algorithm_engine.id'], name='fk_study_algorithm_engine_id'),
    sa.ForeignKeyConstraint(['study_version_id'], ['study_version.id'], name='fk_study_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eligibility_criteria_info')
    # ### end Alembic commands ###
