"""Changes for adding values to study criteria.

Revision ID: d1044e7926c5
Revises: 4ff089373353
Create Date: 2025-02-07 15:06:19.736395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1044e7926c5'
down_revision = '4ff089373353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('criterion_value_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('criterion_staging', sa.Column('echc_value_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.drop_column('criterion_staging', 'values')
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               existing_nullable=False)
    op.add_column('criterion_staging', sa.Column('values', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    op.drop_column('criterion_staging', 'echc_value_ids')
    op.drop_column('criterion_staging', 'criterion_value_ids')
    # ### end Alembic commands ###
