"""Fix cascade delete pre_anonotated_model.

Revision ID: ddada803c81e
Revises: 276d1e9b029e
Create Date: 2025-09-09 13:41:40.925166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddada803c81e'
down_revision = '276d1e9b029e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pre_annotated_criterion_model_pre_annotated_criterion_id_fkey'), 'pre_annotated_criterion_model', type_='foreignkey')
    op.create_foreign_key('pre_annotated_criterion_model_pre_annotated_criterion_id_fkey', 'pre_annotated_criterion_model', 'pre_annotated_criterion', ['pre_annotated_criterion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pre_annotated_criterion_model_pre_annotated_criterion_id_fkey', 'pre_annotated_criterion_model', type_='foreignkey')
    op.create_foreign_key(op.f('pre_annotated_criterion_model_pre_annotated_criterion_id_fkey'), 'pre_annotated_criterion_model', 'pre_annotated_criterion', ['pre_annotated_criterion_id'], ['id'])
    # ### end Alembic commands ###
