"""Modified display_rules.priority type string to integer.

Revision ID: f5121de7f85f
Revises: 3c0909b78f1b
Create Date: 2023-01-01 13:55:35.888073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5121de7f85f'
down_revision = '3c0909b78f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('display_rules', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='priority::integer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('display_rules', 'priority',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
